# Generated by Django 4.2.4 on 2024-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='res/dummyProfile.png', upload_to=''),
        ),
    ]
