# Generated by Django 4.2.4 on 2024-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='long_bio',
            field=models.TextField(default='Description not provided by user', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='short_bio',
            field=models.TextField(default='A new Conversafe user', max_length=100),
        ),
    ]
