# Generated by Django 4.2.4 on 2024-04-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_userprofile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=30)),
                ('siteUrl', models.CharField(max_length=500)),
                ('urlNoProtocol', models.CharField(max_length=450)),
                ('siteType', models.CharField(max_length=30)),
            ],
        ),
    ]
