# Generated by Django 5.0.5 on 2024-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_rename_url_userprofile_user_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "English"),
                    ("HINDI", "Hindi"),
                    ("BENGALI", "Bengali"),
                    ("GERMAN", "German"),
                    ("SPANISH", "Spanish"),
                ],
                default="ENGLISH",
                max_length=10,
            ),
        ),
    ]
