# Generated by Django 5.0.5 on 2024-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("hi", "Hindi"),
                    ("bn", "Bengali"),
                    ("de", "German"),
                    ("es", "Spanish"),
                ],
                default="en",
                max_length=10,
            ),
        ),
    ]
