# Generated by Django 5.0.5 on 2024-12-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_userprofile_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "en"),
                    ("HINDI", "hi"),
                    ("BENGALI", "bn"),
                    ("GERMAN", "de"),
                    ("SPANISH", "es"),
                ],
                default="ENGLISH",
                max_length=10,
            ),
        ),
    ]
