# Generated by Django 5.0.5 on 2024-12-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_userprofile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="learn_lang",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "en"),
                    ("HINDI", "hi"),
                    ("BENGALI", "bn"),
                    ("GERMAN", "de"),
                    ("SPANISH", "es"),
                ],
                default="ENGLISH",
                max_length=10,
            ),
        ),
    ]
