# Generated by Django 4.2.4 on 2024-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auser',
            name='firstLogin',
            field=models.BooleanField(default=False),
        ),
    ]
