# Generated by Django 4.2.4 on 2024-04-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_reportedmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportedmessage',
            old_name='room',
            new_name='message',
        ),
    ]
