# Generated by Django 5.0.5 on 2024-12-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_reportedmessage_messagetext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="messageType",
            field=models.CharField(
                choices=[
                    ("NORMAL", "Normal"),
                    ("JOINED", "Joined"),
                    ("LEFT", "Left"),
                    ("SUGEST", "Suggest"),
                ],
                default="NORMAL",
                max_length=6,
            ),
        ),
    ]
