# Generated by Django 4.2.4 on 2024-04-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIChat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
